### ISSUE TITLE
[TokenContract Review] Early exit on same sender and receiver

### ISSUE THREAD

**Issue by ibrizsabin** [balancednetwork/balanced-rust-contracts#45]
## Issue:
[TokenContract Review] Early exit on same sender and receiver

## Severity:
Minor

## Description:
Check if recipient and sender are not same in `execute_transfer` to avoid unnecessary execution and early exit.

## File Name:
contracts/token-contracts/cw-hub-bnusd/src/contract.rs Line No. 97

**Comment by AntonAndell** [comment]
This is a built in function, id say we shouldn't change the standard behavior.
