### ISSUE TITLE
[TokenContract Review] Do Checked Add And Forward Error

### ISSUE THREAD

**Issue by ibrizsabin** [balancednetwork/balanced-rust-contracts#46]
## Severity:
Minor

## Description:
Overflows will panic by default but its better to do checked add and handle errors for better debugging.

## File Name:
contracts/token-contracts/cw-hub-bnusd/src/contract.rs Line No. 258, 318,331, 362.

**Comment by AntonAndell** [comment]
Not sure i understand, could you give a example?

**Comment by AntonAndell** [comment]
This was is also in the bultin token contract
