### ISSUE TITLE
[TokenContract Review] Addr Validate Beforehand For early exit.

### ISSUE THREAD

**Issue by ibrizsabin** [balancednetwork/balanced-rust-contracts#47]
## Severity:
Minor

## Description:
On ExecuteMint check recipient address validity before doing any other execution for early exit.

## File Name:
contracts/token-contracts/cw-hub-bnusd/src/contract.rs Line No. 327

**Comment by AntonAndell** [comment]
I might be a slight optimization but i like breaking down the network address checks first which then reveals the account.
