### ISSUE TITLE
[Assetmanager Review] Ensure transfer amount greater than zero

### ISSUE THREAD

**Issue by ibrizsabin** [balancednetwork/balanced-rust-contracts#52]
## Severity:
Informational

## Description:
 
The amount parameter should be validated to ensure it is not zero or negative before proceeding with the transfer in `transfer_tokens`.

## File Name:
contracts/core-contracts/cw-asset-manager/src/contract.rs Line No. 316

**Comment by AntonAndell** [comment]
It is a Uint so it can't be negative? 
Also this check exists:
 ensure!(!amount.is_zero(), ContractError::InvalidAmount);
Should that not be sufficient?

**Comment by ibrizsabin** [comment]
ya that should be enough. i must have missed that.
